apiVersion: apps/v1
kind: Deployment
metadata:
  name: upcommerce-main
  namespace: canary-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: upcommerce
      version: main
  template:
    metadata:
      labels:
        app: upcommerce
        version: main
    spec:
      containers:
        - name: upcommerce
          image: uonyeka/upcommerce:main
          ports:
            - containerPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: upcommerce-canary
  namespace: canary-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: upcommerce
      version: canary
  template:
    metadata:
      labels:
        app: upcommerce
        version: canary
    spec:
      containers:
        - name: upcommerce
          image: uonyeka/upcommerce:canary
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: upcommerce-main
  namespace: canary-demo
spec:
  selector:
    app: upcommerce
    version: main
  ports:
    - port: 80
      targetPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: upcommerce-canary
  namespace: canary-demo
spec:
  selector:
    app: upcommerce
    version: canary
  ports:
    - port: 80
      targetPort: 80

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: upcommerce-ingress
  namespace: canary-demo
spec:
  rules:
    - host: canary-demo.local
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: upcommerce-main
              port:
                number: 80
        - path: /canary
          pathType: Prefix
          backend:
            service:
              name: upcommerce-canary
              port:
                number: 80
